/// <reference types="expo/types" />

// expo-env.d.ts (generated by `expo start`, gitignored) holds the same reference; this copy keeps
// `tsc --noEmit` working on a fresh clone. Typed routes are generated into .expo/types.
